server:
  port: 8090

spring:
  kafka:
    consumer:
      group-id: 'product-created-group'
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted-packages: '*'

  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:emaildb
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2